version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB= postgres
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.9.29-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_go_net

volumes:
  db:
    driver: local

networks:
  rabbitmq_go_net:
    driver: bridge